import { ColorSchemeScript, MantineProvider } from "@mantine/core"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider withCssVariables>
          {children}
        </MantineProvider>
      </body>
    </html>
  )
}
